/******** DO NOT EDIT THIS FILE ********/
import java.util.Arrays;

/* 
 * Reading definition - corresponds to one line in the CSV file
 */
public class Reading {
	private String sensorId; //A unique sensor identifier e.g. A, B, C, etc.
	private long timestamp;  //UNIX timestamp of the reading
	private float[] values = new float[3]; //an array of float to store measured values [value1: Temperature, value2: Humidity, value3: Pressure]

	/* constructor */
	public Reading(String sensorId, long timestamp, float[] values) {
		this.sensorId = sensorId;
		this.timestamp = timestamp;
		this.values = values;
	}

	/* string representation of a reading, can be used when storing the reading inside the segment payload */
	@Override
	public String toString() {
		return sensorId + "," + timestamp + "," + Arrays.toString(values);
	}
}