/******** DO NOT EDIT THIS FILE ********/
import java.io.Serializable;
import java.util.zip.CRC32;

//Segment type - either Data segment, Acknowledgment segment or Metadata segment
enum SegmentType {
	Data, Ack, Meta 
}

/* 
 * Segment definition for communication between client and server.
 * The client uses it to transfer either metadata (metadata stored in the payload) or data (readings stored in the payload) to the server. 
 * The server uses it to respond with an ACK. 
 * The segment type determines its specific purpose. 
 */
public class Segment implements Serializable {

	private static final long serialVersionUID = 1L;
	private int size;                 //size of the payload
	private int seqNum;               //sequence number of the segment
	private SegmentType type;         //segment type
	private String payload;          //payload data (metaData or patch-size number of readings)
	private long checksum;           //checksum of the payload

	/* default constructor*/
	public Segment() {}

	/* constructor to set all the attributes including the checksum. */
	public Segment(int seqNum, SegmentType type, String payload, int size) {
		this.seqNum = seqNum;
		this.type = type;
		this.size = size;
		this.payload = payload;
		this.checksum = calculateChecksum();
	}

	/* Calculate the crc checksum of the payload. */
	public long calculateChecksum() {
		CRC32 crc = new CRC32();
		if (payload != null)
			crc.update(payload.getBytes());
		return crc.getValue();
	}

	/* Validates the checksum */
	public boolean isValid() {
		// Check if the stored checksum matches the recalculated one
		return this.checksum == calculateChecksum();
	}


	/* getter and setter methods */
	public int getSize() {
		return size;
	}
	public void setSize(int size) {
		this.size = size;
	}
	public int getSeqNum() {
		return seqNum;
	}
	public void setSeqNum(int sq) {
		this.seqNum = sq;
	}
	public SegmentType getType() {
		return type;
	}
	public void setType(SegmentType type) {
		this.type = type;
	}
	public String getPayLoad() {
		return payload;
	}
	public void setPayLoad(String payLoad) {
		this.payload = payLoad;
	}
	public long getChecksum() {
		return checksum;
	}
	public void setChecksum(int checksum) {
		this.checksum = checksum;
	}
}
